// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mgdnidumcobdpomtgzek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1nZG5pZHVtY29iZHBvbXRnemVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzODkyNzksImV4cCI6MjA3Mzk2NTI3OX0.zFuOhp3UCnsg2SgNDkNHab5L88b7-Gcd0zJbhq09n2Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});